### ISSUE TITLE
Which Azure Subscription I should use to pull data from O365 to Azure ?

### ISSUE THREAD

**Issue by dips23** [microsoftgraph/msgraph-training-dataconnect#6]
Hello,

Thank you for this training lab and I am currently in process of configuring MGDC for my O365 E3 tenant ( GA - user@123.onmicrosoft.com ) , however considering the Azure resources creation , Do I have to use the Azure tenant which is associated with O365 account ( GA - user@123.onmicrosoft.com ) ? 

Or I can pull data from O365 tenant ( GA - user@123.onmicrosoft.com) to another Azure tenant ( GA - azureuser@gmail.com ) ?

Would you please clarify this miss-understanding I have ?

Best Regards,
Dipti Chhatrapati

**Comment by RickVanRousselt** [comment]
Hi Dipti, 
I was also playing around with this. It appears that for now only the Azure environment linked to the Office 365 tenant can get access to the data. I also tried myself to get a demo tenants data into my own tenant but was not successful. But it's specified in the documentation that it's not possible (for now)

**Comment by dips23** [comment]
Thank You Rick for clarifying it,

Maybe transferring the Azure subscription associated with different account to the Office 365 account could do, however wondering how feasible it would be at organization level in such scenario.

Also, I could not find out in prerequisite section mentioning It must be same account for Office 365 and Azure subscriptions as indicated in following screen:

![image](https://user-images.githubusercontent.com/13658386/51302060-44303e00-1a57-11e9-96c7-0eb1f0299c02.png)

Can you please address the line in the documentation ? ( Not sure where I am miss leaded :( )

Thank you for your time !

Best Regards,
Dipti Chhatrapati

**Comment by andrewconnell** [comment]
Graph Data Connect requires you use an Azure subscription that is in the same tenant as Office 365. This is part of the data protection / security aspect of the product (was noted in the docs, not in this lab). I added a note to the prerequs about this to address the issue
