### ISSUE TITLE
Microsoft Graph data connect preview - Unable to retrieve settings

### ISSUE THREAD

**Issue by z442a9** [microsoftgraph/msgraph-training-dataconnect#8]
I tried to configure this but for some reason I cannot enable "Microsoft Graph data connect preview" in Office 365 portal. If I try to enable it it gives error: Unable to retrieve settings

This seems to be a license error. What licenses do we need in our Office 365 tenant?

**Comment by jasonjoh** [comment]
@andrewconnell @rob-windsor do you guys know?

@z442a9 are you still having this problem?

**Comment by andrewconnell** [comment]
You need a **Workplace Analytics** license to use GDC... this was new when GDC went GA at Build 2019. The module has been updated to state this as part of the requirements.
